export const metadata = { title: "AI Disclosure" };

export default function AiDisclosurePage() {
  return (
    <article className="space-y-6">
      <h1 className="text-3xl font-bold tracking-tight">AI Disclosure</h1>

      <p>
        All images produced by Thumbly are generated by an AI model. They
        are not photographs, do not depict real events, and may contain
        artifacts or inaccuracies.
      </p>

      <h2 className="mt-6 text-xl font-semibold">Model and providers</h2>
      <p>
        We use OpenAI&apos;s image generation model and moderation API.
        Inputs (prompts and reference images) are sent to OpenAI for
        processing. OpenAI does not use API content to train its models by
        default.
      </p>

      <h2 className="mt-6 text-xl font-semibold">Content policy</h2>
      <p>
        Every prompt is screened by OpenAI&apos;s moderation API and our
        own blocklist before a credit is spent. We block sexual, violent,
        hateful, and impersonation content. Users may not generate
        likenesses of public figures without consent.
      </p>

      <h2 className="mt-6 text-xl font-semibold">Disclosure on YouTube</h2>
      <p>
        YouTube&apos;s rules require creators to disclose &quot;altered or
        synthetic content&quot; that could mislead viewers. Most thumbnails
        do not require disclosure, but you should review YouTube&apos;s
        guidance for your specific video.
      </p>
    </article>
  );
}
